# Generated by Django 4.1.3 on 2022-12-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiritualcamp',
            name='family_members',
            field=models.PositiveIntegerField(),
        ),
    ]
