# Generated by Django 4.1.3 on 2022-12-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('event_date', models.DateTimeField()),
                ('small_descripton', models.CharField(max_length=50)),
                ('link', models.URLField()),
            ],
        ),
    ]
