# Generated by Django 4.1.3 on 2022-12-03 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagehandling', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
