# Generated by Django 4.1.3 on 2022-12-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagehandling', '0002_rename_events_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='small_descripton',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
