# Generated by Django 4.1.3 on 2022-12-03 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagehandling', '0003_alter_event_small_descripton_alter_event_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='link',
        ),
    ]
