# Generated by Django 4.1.3 on 2022-12-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagehandling', '0004_remove_event_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
