# Generated by Django 4.1.3 on 2022-12-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagehandling', '0005_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Feedback',
        ),
    ]
