# Generated by Django 4.1.3 on 2022-12-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagehandling', '0007_spiritualplaybooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='id',
        ),
        migrations.RemoveField(
            model_name='spiritualplaybooking',
            name='id',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='mobile_number',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='spiritualplaybooking',
            name='mobile_number',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
